### ISSUE TITLE
Error 174:12

### ISSUE THREAD

**Issue by chrixmll** [mystery123sk/Notion-Book-Quote-Management#2]
I followed your steps but… any help on this? Can’t seem to get it working 

If exported as js to files its line 172, but same error

![AA607E30-57B5-4EE7-88A6-142F2B580F48](https://user-images.githubusercontent.com/42547606/212479621-00f66634-3639-4854-94c1-85333b4e51ff.jpeg)

**Comment by chrixmll** [comment]
Copy paste error, sorry my bad

**Comment by C00lplayer** [comment]
> Copy paste error, sorry my bad

I have that error as well, how did u fix it?
